name = "collective-club"
client_id = "b4e0f05c3b167ee4454a2bb3785bf717"
application_url = "https://localhost:3000/"
embedded = false

[access_scopes]
scopes = "read_content,read_customers,write_content,write_customers"

[auth]
redirect_urls = [
  "https://localhost:3000/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true